package com.morphgen.synexis.enums;

public enum JobStatus {
    
    PENDING,
    APPROVED_BY_SALESMANAGER,
    REJECTED_BY_SALESMANAGER,
    APPROVED,
    REJECTED_BY_ACCOUNTANT,
    READY_FOR_DESIGNING,
    READY_FOR_PRODUCTION,
    ONGOING,
    BLOCKED,
    WAITING_FOR_MATERIALS,
    COMPLETED,
    CLOSED
}
